# Generated by Django 3.2.4 on 2021-09-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_auto_20210909_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='nationality',
            field=models.CharField(choices=[('1', 'Rwandan'), ('2', 'Kenyan'), ('3', 'Ugandan'), ('4', 'SouthSudanes'), ('5', 'Sudanes')], max_length=15),
        ),
    ]
